name: Audit

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      DASHBOARD_TOKEN: ${{ secrets.DASHBOARD_TOKEN }}
      INGEST_URL: ${{ secrets.INGEST_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm exec tsx scripts/run-audit.js
      - uses: actions/upload-artifact@v4
        with:
          name: audit-json
          path: audit.json
